DavLockDB /var/lock/apache2/DavLock

<VirtualHost *:80>
    DocumentRoot /var/lib/dav

    <Directory /var/lib/dav>
        Dav On
        Options Indexes FollowSymLinks
        AllowOverride None
        
        AuthType Digest
        AuthName "DYNAMIC_REALM_PLACEHOLDER"
        AuthUserFile /etc/apache2/users.passwd
        Require valid-user

        # Minimalist text view index
        IndexOptions ScanHTMLTitles VersionSort NameWidth=* SuppressIcon
        IndexStyleSheet "/nord-theme.css"

        # Force Apache to show absolutely every file hidden on disk
        IndexIgnore None
    </Directory>

    <Files "nord-theme.css">
        Require all granted
    </Files>
</VirtualHost>
